### ISSUE TITLE
Undefined method `accept' for #<Refile::Attacher:...>

### ISSUE THREAD

**Issue by ohenrik** [hyperoslo/refile-input#1]
Getting this error after upgrading to Refile from master. This is probably something they changed that isn't present in 0.5.5. Pl0x f0x, @toothfairy.

![screen shot 2015-06-16 at 11 33 02](https://cloud.githubusercontent.com/assets/647617/8180063/9f65dbe0-141b-11e5-995d-037c9ec6e8e1.png)

**Comment by jgorset** [comment]
Also worth noting that this is @sindrenm, not @ohenrik. Hue hue.

**Comment by ohenrik** [comment]
This is true!

**Comment by sindrenm** [comment]
What do you mean, @jgorset? Surely @ohenrik is @ohenrik. Can't you read? Do you hate letters? Why do you hate letters so much?

**Comment by sindrenm** [comment]
Great issue, however! Much appreciated if you could accompany that with a just as awesome pull request, @ohenrik. :muscle:

**Comment by zenangst** [comment]
![tumblr_miw9rk9gxs1r7f4pto1_400](https://cloud.githubusercontent.com/assets/57446/8194626/060c6a7e-147d-11e5-9888-0534ceef180b.gif)

**Comment by ohenrik** [comment]
I might try to do that @sindrenm :)

**Comment by toothfairy** [comment]
Oh I thought I replied yesterday. Fix is actually super simple: https://github.com/refile/refile/blob/20ecdb3d760b8eed2d5f4bddf6dd8c673063bf2c/lib/refile/rails/attachment_helper.rb#L66
Also dependency in gemspec needs to be updated

**Comment by sindrenm** [comment]
Since this isn't released (tagged) yet on Refile's end, we might want to keep this on a separate feature branch until the next version comes out, by the way. :smiley:

**Comment by sindrenm** [comment]
And awesome, @ohenrik and @toothfairy!

**Comment by toothfairy** [comment]
@sindrenm it's tagged with 0.5.5 version

**Comment by sindrenm** [comment]
Oh. Then we totally release. :+1:

**Comment by ghost** [comment]
This issue seems to be fixed in refile 0.5.5, but Refile::Attacher#accept is not implemented in refile 0.6.2 (I'm using `refile (0.6.2)`, `refile-input (0.0.3)`).  I've patched my gem on my local machine, adding the `accept` method and `initialize` & `attr_reader` code, and that seems to work.  I don't feel that I know enough about refile to take this further, but I could PR the changes I made to 0.6.2 if you like.

**Comment by toothfairy** [comment]
@davidjsevans sure thing, feel free to submit PR!

**Comment by sindrenm** [comment]
Ahh, thanks for the heads up, @davidjsevans! Yeah, like @toothfairy said, we'd love to see a PR for this. :smile:

**Comment by ghost** [comment]
@toothfairy @sindrenm thanks for the encouragement, find my PR at https://github.com/hyperoslo/refile-input/pull/2

**Comment by toothfairy** [comment]
Closed by PR https://github.com/hyperoslo/refile-input/pull/2

**Comment by sindrenm** [comment]
I'm not gonna say I told you so.

**Comment by toothfairy** [comment]
@sindrenm :ghost:
